### ISSUE TITLE
Feedback on second submission

### ISSUE THREAD

**Issue by Anisha7** [Connor-Cahill/Core-Datastructures-Algorithms#2]
Good job on completing the second coding challenge. Here's some feedback to improve:
- Your LinkedQueue fails tests currently because your front() method is returning the NODE instead of the DATA. Change it to return the data that Node holds.
- Write some tests for your Deque for the extra point. Testing code is always good practice.
- In your sets test, I recommend not use ’set’ as a variable name because python has an inbuilt set module, and it may cause issues.
- Sets missing size property. This is required for full credit.
- Your medium post is under 800 words. 800-1000 words is required!

**Comment by Connor-Cahill** [comment]
Is adding size property not redundant if we can just use the size property from the underlying hashtable? The Sets length() method works fine and passes tests.
